### ISSUE TITLE
Netifd compile error

### ISSUE THREAD

**Issue by ProtoThis** [OpenHisiIpCam/wrt-hisicam#1]
Hi,

Currently I am trying to compile wrt-hisicam for 3816ev200, but I am running into an error. While building the openwrt image it fails on building the netifd package with the following error:

`/home/build/projects/wrt-hisicam/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/netifd-2019-08-05-5e02f944/system-linux.c: At top level:
cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
cc1: all warnings being treated as errors
make[6]: *** [CMakeFiles/netifd.dir/build.make:349: CMakeFiles/netifd.dir/system-linux.c.o] Error 1
make[6]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/netifd-2019-08-05-5e02f944'
make[5]: *** [CMakeFiles/Makefile2:76: CMakeFiles/netifd.dir/all] Error 2
make[5]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/netifd-2019-08-05-5e02f944'
make[4]: *** [Makefile:130: all] Error 2
make[4]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/netifd-2019-08-05-5e02f944'
make[3]: *** [Makefile:49: /home/build/projects/wrt-hisicam/openwrt/build_dir/target-arm_cortex-a7_musl_eabi/netifd-2019-08-05-5e02f944/.built] Error 2
make[3]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt/package/network/config/netifd'
time: package/network/config/netifd/compile#0.27#0.04#0.32
make[2]: *** [package/Makefile:113: package/network/config/netifd/compile] Error 2
make[2]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt'
make[1]: *** [package/Makefile:107: /home/build/projects/wrt-hisicam/openwrt/staging_dir/target-arm_cortex-a7_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/build/projects/wrt-hisicam/openwrt'
make: *** [/home/build/projects/wrt-hisicam/openwrt/include/toplevel.mk:227: world] Error 2`

I am building on a debian 10 system (but have also tried on ubuntu). It appears as if it is passing the no-unknown-warning-option option to gcc which doesn't support this (as it is specific to clang).

With kind regards,

ProtoThis

**Comment by nikitos1550** [comment]
Hi!

Proper config for openwrt is missed in repo.
[config.seed.txt](https://github.com/OpenHisiIpCam/wrt-hisicam/files/5101616/config.seed.txt) You can try this one, put it in openwrt dir named as .config. But I am not sure, still there are a lot of work for openwrt.

I suggest you start with https://github.com/OpenHisiIpCam/br-hisicam
Also you can try prebuilt images https://github.com/OpenHisiIpCam/wrt-hisicam/releases/tag/v0.0.1-alpha

**Comment by ProtoThis** [comment]
Cool, thank you very much :). Will also try the prebuild images, really interested in seeing it boot :). Would make for a nice (cheap) camera :).

**Comment by nikitos1550** [comment]
This is empty firmware, no video software yet. 
Maybe leter.

**Comment by ProtoThis** [comment]
I know, but it will give me a nice base to work with :-).

**Comment by nikitos1550** [comment]
Sure, If any questions you can contact me via telegram @nikita1550
